spring.application.name=journalApp

# Spring + MongoDb Connection properties
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journaldb

# Can configure the Username and Password if required from the database standpoint
#spring.data.mongodb.username=myJournalUser
#spring.data.mongodb.password=myJournalPassword